# Generated by Django 4.1.2 on 2025-01-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attractions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите заголовок', max_length=100, verbose_name='заголовок')),
                ('picture', models.ImageField(help_text='Вставьте фото', null=True, upload_to='images')),
                ('description', models.TextField(help_text='Введите описание', max_length=1000, verbose_name='Описание')),
            ],
        ),
    ]
