# Generated by Django 4.1.2 on 2025-01-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attractions',
            name='description',
            field=models.TextField(blank=True, help_text='Введите описание', max_length=1000, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='attractions',
            name='picture',
            field=models.ImageField(blank=True, help_text='Вставьте фото', null=True, upload_to='images'),
        ),
    ]
