# Generated by Django 4.1.2 on 2025-01-30 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_attractions_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attractions',
            name='source',
            field=models.CharField(default='unknown', help_text='Укажите город', max_length=100, verbose_name='Город'),
        ),
    ]
