# Generated by Django 4.1.2 on 2025-02-09 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_weathercache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attractions',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='attractions',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='attractions',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Заголовок'),
        ),
    ]
