# Generated by Django 5.2.7 on 2026-01-16 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_news'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='news',
            table='app_news',
        ),
    ]
